# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ML Engineering
author: Joaquin Vanschoren
logo: notebooks/images/banner.jpeg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  exclude_patterns:
    - 'Lab*'
    - 'Tutorial*'
    - 'X*'
    - 'S*'
    - '05*'
    - '06*'
    - '07*'
    - '08*'
    - '09*'
    - '10*'

# Include slides
sphinx:
  config:
    html_extra_path: ['slides_html']

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ml-course/master  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  
launch_buttons:
  colab_url: "https://colab.research.google.com"
